### PR TITLE
Issue#23 FIXED

### LINKED ISSUE #20: json.Unmarshall error while using sdp from browser for pub-from-browser example
### Your environment.
  - Version: *0dd6b83fa52f9726695a59e4699537da9e6becbb*
  - OS: *Arch Linux*
  - Browser: *Google Chrome Version 81.0.4044.129 (Official Build) (64-bit)*

### What did you do?
I was following the examples code for **pub-from-browser**

I copied the **base64 sdp** from from top text are of **jsfiddle** in expample **README.md**

Pasted sdp to sdp.txt
then,

`cat sdp.txt | go run pub_from_browser/main.go`

### What did you expect?
I expected to get an another sdp to paste in jsfiddle and start the session

### What happened?
Then I get following error traceback:

```
[wrocket@wrocket-pc pub-from-browser]$ cat sdp.txt | go run main.go

panic: illegal base64 data at input byte 1

goroutine 1 [running]:
github.com/pion/ion-sfu/examples/internal/signal.Decode(0xc000016a00, 0x2124, 0x94e3a0, 0xc000074af0)
	/home/wrocket/git/ion-sfu/examples/internal/signal/signal.go:74 +0xbf
main.main()
	/home/wrocket/git/ion-sfu/examples/pub-from-browser/main.go:30 +0x20d
exit status 2
```

I found the **sdp value in json is string** and `Sdp` in `SDPDescription` struct  in proto3 is []byte.
And because of it we are having issue in `json.Unmarshall `

### PR DESCRIPTION
**Pull request by Wrufesh**
#### Description
Fixes json.Unmarshall error while using sdp from browser for pub-from-browser example

#### Reference issue
Fixes #20

### CODE REVIEW

**Comment by tarrencev** [comment]
Awesome thanks! If you have a few mins, the `pub-from-disk` example needs this fix too :)

**Comment by Wrufesh** [comment]
I would love to try it again.

**Comment by Wrufesh** [comment]
> Awesome thanks! If you have a few mins, the `pub-from-disk` example needs this fix too :)

I think its a dummy question. Still, we are using `webrtc/v2` in pub-from-browser and `webrtc/v3` in pub-from-disk.
Is it intensional? I am sorry if question is bad but I am totally new to goland and its webrtc implementation by pion. I am very much exited to use `ion-sfu` with grpc and integrate it to my existing app and scale.

**Comment by tarrencev** [comment]
Not a dummy question at all! I think the `pub-from-browser` example was created before `pub-from-disk` and when i did `pub-from-disk` v3 was out. I actually didn't notice that was the case. We are moving everything to v3 soon, so we can probably leave it for now

**Comment by Wrufesh** [comment]
> Not a dummy question at all! I think the `pub-from-browser` example was created before `pub-from-disk` and when i did `pub-from-disk` v3 was out. I actually didn't notice that was the case. We are moving everything to v3 soon, so we can probably leave it for now

I didnt find any `json.Unmarshall` issue in `pub-from-disc`. Sdp was not printed in an output but can see Sdp in `ion-sfu` log. So what should be fixed in `pub-from-disc`.

**Comment by tarrencev** [comment]
Ok then i guess it is fine. Thanks for taking a look!

**Pull request merged**
