### PR TITLE
add media-device broadcast example

### PR DESCRIPTION
**Pull request by mohammadne**
HI @Sean-Der 

#### Description
add `media-device broadcast` example which `Go` peer will publish camera of itself
and the other `JS` peer will consume the media

### CODE REVIEW

**Comment by mohammadne** [comment]
@Sean-Der 
any update ?

**Comment by adwpc** [comment]
@mohammadne 
`# github.com/pion/mediadevices
../../../../../../pkg/mod/github.com/pion/mediadevices@v0.2.0/track.go:342:33: cannot use mtu (type int) as type uint16 in argument to rtp.NewPacketizer
../../../../../../pkg/mod/github.com/pion/mediadevices@v0.2.0/track.go:462:33: cannot use mtu (type int) as type uint16 in argument to rtp.NewPacketizer`
i got this error when use mediadevices@v0.2.0
it worked when i change to mediadevices@v0.3.0
there is no audio

**Comment by mohammadne** [comment]
Hi @adwpc 
I have just updated the `mediadevices`

**Comment by adwpc** [comment]
@mohammadne 
thanks, but i think it's better not to add more examples in ion-sfu/example.
and better to use ion-sdk-go to publish from devices
https://github.com/pion/ion-sdk-go/tree/master/example

**Comment by mohammadne** [comment]
@adwpc  ok, no problem
but in overall I think having the same functionality in both sdk and library can help alot.
thanks for your attention

**Pull request closed without merging**
