### PR TITLE
refactor: upgrade logr/zerologr to stable release v1.0.0

### PR DESCRIPTION
**Pull request by hn8**
#### Description
logr.Logger is changed from interface (v0.4.0) to struct (v1.0.0). Update zerologr to logr.LogSink.

### CODE REVIEW

**Comment by hn8** [comment]
@tarrencev @OrlandoCo Would you please review this PR? It doesn't change any public interface of zerologr, but logr.Logger is changed from interface to struct in the stable release, so nil check is replaced.

**Comment by adwpc** [comment]
@hn8 Thanks.

**Comment by hn8** [comment]
@adwpc Do you know how can I proceed for this commit? Can't believe logger change would change test coverage so much since this package is not about logging? Lol

**Comment by adwpc** [comment]
> @adwpc Do you know how can I proceed for this commit? Can't believe logger change would change test coverage so much since this package is not about logging? Lol

seems not your fault
i met this on ion too

**Review by adwpc — APPROVED** [review]

**Review by tarrencev — APPROVED** [review]

**Pull request merged**
