### PR TITLE
add metadata field to peer structure

### PR DESCRIPTION
**Pull request by nkonev**
#### Description

It can be set from backend code. It can consist any data, in order to help to filter queriable peers.
Example of usage: (Let's imagine I want to reimplement Zoom-like 40 free minutes feature)
```go
func closeNonPaid(session *sfu.Session) {
	for _, peer := range session.Peers() {
		if m := peer.Metadata(); m != nil {
			pi := m.(*PaymentInfo)
			if !enoughMoney(pi) {
				peer.Close()
				session.RemovePeer(peer.ID())
			}
		}
	}
}
```

### CODE REVIEW

**Comment by tarrencev** [comment]
hi @nkonev , it is possible to handle this at the application level. i.e. inside of grpc/json rpc signaling logic.

**Comment by nkonev** [comment]
Hello @tarrencev 
Can you please describe your thoughts ?
I have in mine proposal

```main.go
	http.Handle("/ws", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		c, err := upgrader.Upgrade(w, r, nil)
		if err != nil {
			panic(err)
		}
		defer c.Close()

		p := server.NewJSONSignal(sfu.NewPeer(s), logger)
		defer p.Close()

		jc := jsonrpc2.NewConn(r.Context(), websocketjsonrpc2.NewObjectStream(c), p)
		<-jc.DisconnectNotify()
	}))

http.Handle("/ws", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
	chatId := r.URL.Query().Get("chatId")
	userToKickId := r.URL.Query().Get("userId")

	// for peer := session.peers
	session, _ := h.sfu.GetSession(fmt.Sprintf("chat%v", chatId)) // ChatVideo.vue
	if session == nil {
		return
	}
	for _, peerF := range session.Peers() {
		gotUserId := peerF.Metadata()
		i := gotUserId.(string)
		if userToKickId == i {
			peerF.Close()
			session.RemovePeer(peerF.ID())
		}
	}
}))
```

Sorry for dummy question, but how to implement it with jsonrpc level ?
Do I need some map of `*jsonrpc2.Conn` which will be cleaned by periodic goroutine ?
The additional metadata field looks simpler that map of `*jsonrpc2.Conn` which will be cleaned by periodic goroutine

**Comment by billylindeman** [comment]
@tarrencev agreed this could be done application level.  Custom signal logic can be implemented by wrapping the peer struct like the example jsonrpc signal server https://github.com/pion/ion-sfu/blob/master/cmd/signal/json-rpc/server/server.go#L33

**Comment by nkonev** [comment]
@billylindeman @tarrencev 
thank you for responses.

Do you mean something like
```
type WrappedPeer struct {
	*sfu.Peer
	token string
}
...
server.NewJSONSignal(WrappedPeer{sfu.NewPeer(h.sfu), token}, logger)
...
http.Handle("/admin/kick", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
	chatId := r.URL.Query().Get("chatId")
	toKick := r.URL.Query().Get("token")

	// for peer := session.peers
	session, _ := h.sfu.GetSession(fmt.Sprintf("chat%v", chatId))
	if session == nil {
		return
	}
	for _, peerF := range session.Peers() {
		converted := peerF.(WrappedPeer)
		if converted.token == toKick {
			peerF.Close()
			session.RemovePeer(peerF.ID())
		}
	}
}))
```

?

In order to do that we need to change signature `func NewJSONSignal(p *sfu.Peer, l logr.Logger) *JSONSignal` in order to it accepts the peer interface because pointers in Go doesn't castable, isnt't it ?

**Comment by nkonev** [comment]
Seems I did it with connection map like that
```go
 struct {
	client      *http.Client
	upgrader    *websocket.Upgrader
	sfu         *sfu.SFU
	conf        *config.ExtendedConfig
	httpFs      *http.FileSystem
	connections connectionsLockableMap
}

type connectionWithData map[*sfu.Peer]string
type connectionsLockableMap struct {
	sync.RWMutex
	connectionWithData
}

func (h *Handler) SfuHandler(w http.ResponseWriter, r *http.Request) {
	userId := r.Header.Get("X-Auth-UserId")
	chatId := r.URL.Query().Get("chatId")
	if !h.checkAccess(h.client, userId, chatId) {
		w.WriteHeader(http.StatusUnauthorized)
		return
	}

	c, err := h.upgrader.Upgrade(w, r, nil)
	if err != nil {
		panic(err)
	}
	defer c.Close()

	peer0 := sfu.NewPeer(h.sfu)
	h.addToConnMap(peer0, userId)
	defer h.removeFromConnMap(peer0, userId)
	p := server.NewJSONSignal(peer0, logger)
	defer p.Close()

	jc := jsonrpc2.NewConn(r.Context(), websocketjsonrpc2.NewObjectStream(c), p)
	<-jc.DisconnectNotify()
}

func (h *Handler) addToConnMap(peer0 *sfu.Peer, userId string) {
	logger.Info("Adding peer to map", "peer", peer0.ID(), "userId", userId)
	h.connections.Lock()
	defer h.connections.Unlock()
	h.connections.connectionWithData[peer0] = userId
}

func (h *Handler) removeFromConnMap(peer0 *sfu.Peer, userId string) {
	logger.Info("Removing peer from map", "peer", peer0.ID(), "userId", userId)
	h.connections.Lock()
	defer h.connections.Unlock()
	delete(h.connections.connectionWithData, peer0)
}

func (h *Handler) getFromConnMap(peer0 *sfu.Peer) string {
	h.connections.RLock()
	defer h.connections.RUnlock()
	s, ok := h.connections.connectionWithData[peer0]
	if ok {
		return s
	} else {
		return ""
	}
}

func (h *Handler) Kick(w http.ResponseWriter, r *http.Request) {
	chatId := r.URL.Query().Get("chatId")
	userToKickId := r.URL.Query().Get("userId")
	h.kick(chatId, userToKickId)
}

func (h *Handler) kick(chatId, userId string) {
	// for peer := session.peers
	session, _ := h.sfu.GetSession(fmt.Sprintf("chat%v", chatId)) // ChatVideo.vue
	if session == nil {
		return
	}
	for _, peerF := range session.Peers() {
		if userId == h.getFromConnMap(peerF) {
			peerF.Close()
			session.RemovePeer(peerF.ID())
		}
	}
}
```

**Pull request closed without merging**
