### PR TITLE
Add support for grpc-web.

### PR DESCRIPTION
**Pull request by cloudwebrtc**
#### Description

Using the same port for grpc and grpc-web.

Related
https://github.com/pion/ion-sdk-js/pull/77
https://github.com/pion/ion-sdk-flutter/pull/29

#### Reference issue
Fixes #...

### CODE REVIEW

**Comment by billylindeman** [comment]
Nice! Does this work with https://github.com/improbable-eng/grpc-web/tree/master/client/grpc-web?

**Comment by cloudwebrtc** [comment]
> Nice! Does this work with https://github.com/improbable-eng/grpc-web/tree/master/client/grpc-web?

Yes, it runs very well.
I am trying to connect the flutter web, ts, and flutter native using grpc/grpc-web.

**Comment by tarrencev** [comment]
i wonder if it would be simpler to just provide an envoy config

**Comment by cloudwebrtc** [comment]
grpc-web does not provide bidirectional streaming, and grpc web proxy is
required to provide websocket transport. I don’t know if envoy can make
grpc-web support bidirectional streaming.

Tarrence van As <notifications@github.com> 于 2020年10月22日周四 10:12写道：

**Comment by adwpc** [comment]
i think envoy support bidirectional grpc

**Comment by cloudwebrtc** [comment]
> i wonder if it would be simpler to just provide an envoy config

Now the PR supports grpc/grpc-web to use the same port, so we don't need to add envoy proxy.

**Comment by adwpc** [comment]
LGTM

**Review by adwpc — APPROVED** [review]

**Pull request merged**
